#!/usr/bin/env bash
# One-command IP lab deploy for a Linux host that has Docker, an IP, and no DNS name.
# Keep generated values in sync with ops/self-hosted/scripts/ip-lab-profile.ts.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
compose_dir="$(cd "${script_dir}/.." && pwd)"
env_file="${compose_dir}/.env"

host=""
tls_mode="http"
admin_username="admin.ops"
admin_password=""
force="false"
skip_build="false"
command="all"

usage() {
  cat <<EOF
Usage: $(basename "$0") [options] [init|preflight|up|provision|all]

  --ip, --host ADDR       Public or LAN IP clients will use (required if auto-detect fails)
  --tls-mode http|internal
  --admin-username NAME   Default: admin.ops
  --admin-password PASS   Generated when omitted
  --force                 Overwrite an existing .env
  --skip-build            Start containers without rebuilding images
  --env-file PATH         Default: ops/self-hosted/.env

This profile is a lab/demo path. It does not claim commercial-pilot or release readiness.
EOF
}

url_safe_secret() {
  openssl rand -hex 16
}

detect_host() {
  local candidate=""
  if command -v hostname >/dev/null 2>&1; then
    candidate="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
  fi
  if [ -z "${candidate}" ] && command -v ip >/dev/null 2>&1; then
    candidate="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i = 1; i <= NF; i++) if ($i == "src") { print $(i + 1); exit } }' || true)"
  fi
  printf '%s\n' "${candidate}"
}

public_url() {
  local site_host="$1"
  local mode="$2"
  if [ "${mode}" = "internal" ]; then
    printf 'https://%s\n' "${site_host}"
  else
    printf 'http://%s\n' "${site_host}"
  fi
}

caddyfile_for_mode() {
  if [ "$1" = "internal" ]; then
    printf 'Caddyfile.ip-lab-tls\n'
  else
    printf 'Caddyfile.ip-lab\n'
  fi
}

write_env() {
  local site_host="$1"
  local mode="$2"
  local username="$3"
  local password="$4"
  local postgres_password
  local minio_password
  local public
  local caddyfile
  postgres_password="$(url_safe_secret)"
  minio_password="$(url_safe_secret)"
  public="$(public_url "${site_host}" "${mode}")"
  caddyfile="$(caddyfile_for_mode "${mode}")"

  cat > "${env_file}" <<EOF
# WiseEff IP lab profile — generated by deploy-ip-lab.sh
WISEEFF_DEPLOY_PROFILE=ip-lab
WISEEFF_TLS_MODE=${mode}
WISEEFF_CADDYFILE=${caddyfile}
WISEEFF_SITE_HOST=${site_host}
WISEEFF_TLS_EMAIL=unused-ip-lab@localhost
WISEEFF_PUBLIC_URL=${public}
WISEEFF_LAB_ADMIN_USERNAME=${username}
WISEEFF_LAB_ADMIN_PASSWORD=${password}
WISEEFF_LAB_ADMIN_NAME=Platform Admin

NODE_ENV=production
HOST=0.0.0.0
PORT=8787

POSTGRES_PASSWORD=${postgres_password}
DATABASE_URL=postgres://wiseeff:${postgres_password}@postgres:5432/wiseeff

AUTH_MODE=production
AUTH_PROVIDER=local
AUTH_OIDC_ISSUER=
AUTH_OIDC_AUDIENCE=
AUTH_OIDC_JWKS_URI=
M6_SELFHOSTED_SMOKE_AUTHORIZATION=
M6_IDENTITY_AUTHORIZATION=
M6_IDENTITY_WRONG_ISSUER_AUTHORIZATION=
M6_IDENTITY_WRONG_AUDIENCE_AUTHORIZATION=
M6_IDENTITY_EXPIRED_AUTHORIZATION=
M5_SMOKE_AUTHORIZATION=
WISEEFF_SMOKE_AUTHORIZATION=

WISEEFF_API_BASE_URL=${public}
VITE_WISEEFF_RUNTIME_MODE=api
VITE_WISEEFF_API_BASE_URL=${public}

MINIO_ROOT_USER=wiseeff
MINIO_ROOT_PASSWORD=${minio_password}
OBJECT_STORE_MODE=s3
OBJECT_STORAGE_ENDPOINT=http://minio:9000
OBJECT_STORAGE_BUCKET=wiseeff
OBJECT_STORAGE_ACCESS_KEY_ID=wiseeff
OBJECT_STORAGE_SECRET_ACCESS_KEY=${minio_password}
OBJECT_STORAGE_REGION=us-east-1
OBJECT_STORAGE_TLS_POLICY=optional
OBJECT_STORAGE_PATH_STYLE=true
OBJECT_STORAGE_HEALTH_PREFIX=.health/
OBJECT_STORAGE_RETENTION_CLASS=pilot-default

BACKUP_DATABASE_TARGET=file:///var/backups/wiseeff/postgres/wiseeff.dump
BACKUP_OBJECT_STORAGE_TARGET=file:///var/backups/wiseeff/object-store/
RESTORE_DATABASE_URL=postgres://wiseeff_restore:restore-password@postgres:5432/wiseeff_restore
RESTORE_OBJECT_STORAGE_BUCKET=wiseeff-restore
RESTORE_OBJECT_STORAGE_PREFIX=m6-drill/

DEBUG_DEVICE_GATEWAY_MODE=multi
DEVICE_GATEWAY_ALLOW_SIMULATOR_IN_PRODUCTION=true
HDC_TIMEOUT_MS=5000
ADB_TIMEOUT_MS=5000

DEVICE_BRIDGE_ARTIFACT_ROOT=ops/self-hosted/bridge-artifacts
DEVICE_BRIDGE_TOOL_ARTIFACT_ROOT=ops/self-hosted/bridge-tool-artifacts
DEVICE_BRIDGE_PAIRING_TTL_SECONDS=1800
DEVICE_BRIDGE_TOKEN_TTL_DAYS=90
DEVICE_BRIDGE_WS_PATH=/api/v1/device-bridges/ws
DEVICE_BRIDGE_LAB_AVAILABLE=false
DEVICE_BRIDGE_SERVER_URL=${public}

AGENT_API_BASE_URL=
AGENT_MODEL=
AGENT_API_KEY=
AGENT_API_TIMEOUT_MS=30000
XIAOZE_CHECKPOINTER=postgres
XIAOZE_DETERMINISTIC=true

LOG_ANALYSIS_API_BASE_URL=
LOG_ANALYSIS_MODEL=
LOG_ANALYSIS_API_KEY=
LOG_ANALYSIS_API_TIMEOUT_MS=30000
LOG_ANALYSIS_TOKEN_BUDGET=8000
LOG_ANALYSIS_DETERMINISTIC=true

LOG_WORKER_ENABLED=false
LOG_ANALYSIS_QUEUE_MODE=durable
REDIS_URL=redis://redis:6379
LOG_ANALYSIS_QUEUE_PREFIX=wiseeff
LOG_ANALYSIS_QUEUE_ATTEMPTS=4
LOG_ANALYSIS_QUEUE_BACKOFF_MS=1000
LOG_ANALYSIS_QUEUE_CONCURRENCY=1

M5_CONTRACT_CHECK_PASSED=true
M5_BACKUP_RESTORE_DRILL_AT=
M5_SMOKE_ALLOW_NO_API=false
EOF
  chmod 600 "${env_file}"
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    if [ "$1" = "docker" ]; then
      echo "Install Docker Engine first: https://docs.docker.com/engine/install/ubuntu/" >&2
    fi
    if [ "$1" = "openssl" ]; then
      echo "Install openssl (Ubuntu: sudo apt-get install -y openssl)" >&2
    fi
    exit 1
  fi
}

env_value() {
  local key="$1"
  awk -F= -v key="${key}" '$1 == key { sub(/^[^=]+=/, ""); print; exit }' "${env_file}"
}

run_init() {
  require_command openssl
  if [ -z "${host}" ]; then
    host="$(detect_host)"
  fi
  if [ -z "${host}" ]; then
    echo "Could not detect a host IP. Re-run with --ip <address>." >&2
    exit 1
  fi
  if [ -z "${admin_password}" ]; then
    admin_password="$(url_safe_secret)"
  fi
  if [ -f "${env_file}" ] && [ "${force}" != "true" ]; then
    echo "${env_file} already exists. Use --force to overwrite, or keep it and continue." >&2
    return 0
  fi
  write_env "${host}" "${tls_mode}" "${admin_username}" "${admin_password}"
  echo "Wrote ${env_file} (mode 600)."
  echo "Lab URL: $(env_value WISEEFF_PUBLIC_URL)"
  echo "Admin username: $(env_value WISEEFF_LAB_ADMIN_USERNAME)"
  echo "Admin password: $(env_value WISEEFF_LAB_ADMIN_PASSWORD)"
}

run_preflight() {
  require_command docker
  if [ ! -f "${env_file}" ]; then
    echo "Missing ${env_file}. Run: $0 --ip <address> init" >&2
    exit 1
  fi

  local profile mode caddyfile public_url site_host postgres_password database_url
  profile="$(env_value WISEEFF_DEPLOY_PROFILE)"
  mode="$(env_value WISEEFF_TLS_MODE)"
  caddyfile="$(env_value WISEEFF_CADDYFILE)"
  public_url="$(env_value WISEEFF_PUBLIC_URL)"
  site_host="$(env_value WISEEFF_SITE_HOST)"
  postgres_password="$(env_value POSTGRES_PASSWORD)"
  database_url="$(env_value DATABASE_URL)"

  [ "${profile}" = "ip-lab" ] || { echo "WISEEFF_DEPLOY_PROFILE must be ip-lab." >&2; exit 1; }
  [ -n "${site_host}" ] || { echo "WISEEFF_SITE_HOST is required." >&2; exit 1; }
  [ -n "${public_url}" ] || { echo "WISEEFF_PUBLIC_URL is required." >&2; exit 1; }
  [ -n "${postgres_password}" ] || { echo "POSTGRES_PASSWORD is required." >&2; exit 1; }
  case "${database_url}" in
    *"${postgres_password}"*) ;;
    *)
      echo "DATABASE_URL must embed the expanded POSTGRES_PASSWORD." >&2
      exit 1
      ;;
  esac
  if [ ! -f "${compose_dir}/${caddyfile}" ]; then
    echo "Missing Caddyfile: ${compose_dir}/${caddyfile}" >&2
    exit 1
  fi
  if [ "${mode}" = "http" ] && [ "${caddyfile}" != "Caddyfile.ip-lab" ]; then
    echo "HTTP lab mode requires WISEEFF_CADDYFILE=Caddyfile.ip-lab." >&2
    exit 1
  fi
  if [ "${mode}" = "internal" ] && [ "${caddyfile}" != "Caddyfile.ip-lab-tls" ]; then
    echo "Internal TLS lab mode requires WISEEFF_CADDYFILE=Caddyfile.ip-lab-tls." >&2
    exit 1
  fi
  if [ "$(env_value AUTH_PROVIDER)" != "local" ]; then
    echo "AUTH_PROVIDER must be local." >&2
    exit 1
  fi
  if [ "$(env_value XIAOZE_DETERMINISTIC)" != "true" ] && [ -z "$(env_value AGENT_API_KEY)" ]; then
    echo "Set XIAOZE_DETERMINISTIC=true or provide AGENT_API_KEY." >&2
    exit 1
  fi
  if [ "$(env_value LOG_ANALYSIS_DETERMINISTIC)" != "true" ] && [ -z "$(env_value LOG_ANALYSIS_API_KEY)" ]; then
    echo "Set LOG_ANALYSIS_DETERMINISTIC=true or provide LOG_ANALYSIS_API_KEY." >&2
    exit 1
  fi

  local avail_mb=""
  if [ -r /proc/meminfo ]; then
    avail_mb="$(awk '/MemAvailable/ {printf "%d", $2 / 1024}' /proc/meminfo)"
    if [ -n "${avail_mb}" ] && [ "${avail_mb}" -lt 800 ]; then
      echo "Refusing to start: MemAvailable=${avail_mb}MB (< 800MB)." >&2
      exit 1
    fi
    if [ -n "${avail_mb}" ] && [ "${avail_mb}" -lt 2048 ]; then
      echo "Warning: MemAvailable=${avail_mb}MB. First image build may OOM; 4GB RAM is safer." >&2
    fi
  fi

  echo "IP lab preflight passed for ${public_url}"
}

run_up() {
  local build_flag=(--build)
  if [ "${skip_build}" = "true" ]; then
    build_flag=()
  else
    echo "Building and starting the stack. The first image build compiles dtc and the frontend and can take several minutes."
  fi
  "${script_dir}/compose" --env-file "${env_file}" up -d "${build_flag[@]}"
}

wait_for_live() {
  local attempt
  echo "Waiting for http://127.0.0.1/health/live ..."
  for attempt in $(seq 1 180); do
    if curl -fsS http://127.0.0.1/health/live >/dev/null 2>&1; then
      echo "API is live."
      return 0
    fi
    sleep 2
  done
  echo "Timed out waiting for /health/live. Check: ${script_dir}/compose --env-file ${env_file} logs --tail=200 api proxy" >&2
  exit 1
}

run_provision() {
  "${script_dir}/compose" --env-file "${env_file}" exec -T api npm run selfhost:ip-lab:provision
}

print_next_steps() {
  cat <<EOF

IP lab is ready.
  URL:      $(env_value WISEEFF_PUBLIC_URL)
  Username: $(env_value WISEEFF_LAB_ADMIN_USERNAME)
  Password: stored in ${env_file} as WISEEFF_LAB_ADMIN_PASSWORD
  Org:      ChargeLab (bundled demo data)

This profile uses local accounts, HTTP or Caddy internal TLS, and deterministic LLM fallbacks.
It is not commercial-pilot evidence.
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --ip|--host)
      host="${2:-}"
      shift 2
      ;;
    --tls-mode)
      tls_mode="${2:-}"
      if [ "${tls_mode}" != "http" ] && [ "${tls_mode}" != "internal" ]; then
        echo "TLS mode must be http or internal." >&2
        exit 1
      fi
      shift 2
      ;;
    --admin-username)
      admin_username="${2:-}"
      shift 2
      ;;
    --admin-password)
      admin_password="${2:-}"
      shift 2
      ;;
    --env-file)
      env_file="${2:-}"
      shift 2
      ;;
    --force)
      force="true"
      shift
      ;;
    --skip-build)
      skip_build="true"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    init|preflight|up|provision|all)
      command="$1"
      shift
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

case "${command}" in
  init)
    run_init
    ;;
  preflight)
    run_preflight
    ;;
  up)
    run_preflight
    run_up
    ;;
  provision)
    run_preflight
    wait_for_live
    run_provision
    print_next_steps
    ;;
  all)
    run_init
    run_preflight
    run_up
    wait_for_live
    run_provision
    print_next_steps
    ;;
  *)
    usage >&2
    exit 1
    ;;
esac
