import {
  caddyfileForTlsMode,
  evaluateIpLabCaddyfile,
  evaluateIpLabEnv,
  formatHostForUrl,
  generateUrlSafeSecret,
  parseEnvText,
  publicUrlForLab,
  renderIpLabEnv,
  type IpLabPreflightResult,
  type IpLabTlsMode
} from "./ip-lab-profile";
import {
  normalizeAnswers,
  type SelfHostAnswers,
  type SelfHostSecrets,
  type SelfHostTlsMode
} from "./selfhost-answers";

export const acmeDeployProfile = "acme";
export const acmeCaddyfile = "Caddyfile.example";

export const requiredAcmeCaddyTokens = [
  "email {$WISEEFF_TLS_EMAIL}",
  "tls {$WISEEFF_TLS_EMAIL}",
  "reverse_proxy api:8787",
  "reverse_proxy web:5173",
  "handle /api/*",
  "handle /health/*"
] as const;

const urlSafeSecretPattern = /^[A-Za-z0-9_-]+$/;

export function publicUrlForSelfHost(host: string, tlsMode: SelfHostTlsMode) {
  if (tlsMode === "acme") {
    return `https://${formatHostForUrl(host)}`;
  }
  return publicUrlForLab(host, tlsMode);
}

export function caddyfileForSelfHost(tlsMode: SelfHostTlsMode) {
  if (tlsMode === "acme") {
    return acmeCaddyfile;
  }
  return caddyfileForTlsMode(tlsMode);
}

export function resolveSecrets(
  existing: Record<string, string | undefined> | undefined,
  force: boolean,
  generate = generateUrlSafeSecret
): SelfHostSecrets {
  const postgresPassword = existing?.POSTGRES_PASSWORD?.trim();
  const minioPassword = existing?.MINIO_ROOT_PASSWORD?.trim();
  if (!force && postgresPassword && minioPassword) {
    return { postgresPassword, minioPassword };
  }
  return {
    postgresPassword: generate(),
    minioPassword: generate()
  };
}

export function renderSelfHostEnv(answers: SelfHostAnswers, secrets: SelfHostSecrets) {
  const normalized = normalizeAnswers(answers);
  if (normalized.profile === "ip-lab") {
    return renderIpLabEnv({
      host: normalized.siteHost,
      tlsMode: normalized.tlsMode as IpLabTlsMode,
      adminUsername: normalized.adminUsername,
      adminPassword: normalized.adminPassword,
      adminName: normalized.adminName,
      seed: normalized.seed,
      postgresPassword: secrets.postgresPassword,
      minioPassword: secrets.minioPassword,
      agentApiBaseUrl: normalized.agentApiBaseUrl,
      agentModel: normalized.agentModel,
      agentApiKey: normalized.agentApiKey,
      logAnalysisApiBaseUrl: normalized.logAnalysisApiBaseUrl,
      logAnalysisModel: normalized.logAnalysisModel,
      logAnalysisApiKey: normalized.logAnalysisApiKey
    });
  }
  return renderAcmeEnv(normalized, secrets);
}

function renderAcmeEnv(answers: SelfHostAnswers, secrets: SelfHostSecrets) {
  if (!urlSafeSecretPattern.test(secrets.postgresPassword)) {
    throw new Error("PostgreSQL password must be URL-safe ([A-Za-z0-9_-]).");
  }
  if (!urlSafeSecretPattern.test(secrets.minioPassword)) {
    throw new Error("MinIO password must be URL-safe ([A-Za-z0-9_-]).");
  }
  if (answers.adminUsername.trim().length < 3) {
    throw new Error("Admin username must be at least 3 characters.");
  }
  if (answers.adminPassword.length < 8) {
    throw new Error("Admin password must be at least 8 characters.");
  }

  const host = answers.siteHost.trim();
  const publicUrl = publicUrlForSelfHost(host, "acme");
  const xiaozeDeterministic = answers.agentApiBaseUrl && answers.agentApiKey ? "false" : "true";
  const logAnalysisDeterministic =
    answers.logAnalysisApiBaseUrl && answers.logAnalysisApiKey ? "false" : "true";

  return [
    "# WiseEff ACME / DNS self-hosted profile — generated by setup.sh.",
    "# Secrets are expanded. This does not claim commercial-pilot readiness.",
    "",
    `WISEEFF_DEPLOY_PROFILE=${acmeDeployProfile}`,
    "WISEEFF_TLS_MODE=acme",
    `WISEEFF_CADDYFILE=${acmeCaddyfile}`,
    `WISEEFF_SITE_HOST=${host}`,
    `WISEEFF_TLS_EMAIL=${answers.tlsEmail}`,
    `WISEEFF_PUBLIC_URL=${publicUrl}`,
    `WISEEFF_LAB_ADMIN_USERNAME=${answers.adminUsername}`,
    `WISEEFF_LAB_ADMIN_PASSWORD=${answers.adminPassword}`,
    `WISEEFF_LAB_ADMIN_NAME=${answers.adminName}`,
    `WISEEFF_LAB_SEED=${answers.seed}`,
    "",
    "NODE_ENV=production",
    "HOST=0.0.0.0",
    "PORT=8787",
    "",
    `POSTGRES_PASSWORD=${secrets.postgresPassword}`,
    `DATABASE_URL=postgres://wiseeff:${secrets.postgresPassword}@postgres:5432/wiseeff`,
    "",
    "AUTH_MODE=production",
    "AUTH_PROVIDER=local",
    "AUTH_OIDC_ISSUER=",
    "AUTH_OIDC_AUDIENCE=",
    "AUTH_OIDC_JWKS_URI=",
    "M6_SELFHOSTED_SMOKE_AUTHORIZATION=",
    "M6_IDENTITY_AUTHORIZATION=",
    "M6_IDENTITY_WRONG_ISSUER_AUTHORIZATION=",
    "M6_IDENTITY_WRONG_AUDIENCE_AUTHORIZATION=",
    "M6_IDENTITY_EXPIRED_AUTHORIZATION=",
    "M5_SMOKE_AUTHORIZATION=",
    "WISEEFF_SMOKE_AUTHORIZATION=",
    "",
    `WISEEFF_API_BASE_URL=${publicUrl}`,
    "VITE_WISEEFF_RUNTIME_MODE=api",
    `VITE_WISEEFF_API_BASE_URL=${publicUrl}`,
    "",
    "MINIO_ROOT_USER=wiseeff",
    `MINIO_ROOT_PASSWORD=${secrets.minioPassword}`,
    "OBJECT_STORE_MODE=s3",
    "OBJECT_STORAGE_ENDPOINT=http://minio:9000",
    "OBJECT_STORAGE_BUCKET=wiseeff",
    "OBJECT_STORAGE_ACCESS_KEY_ID=wiseeff",
    `OBJECT_STORAGE_SECRET_ACCESS_KEY=${secrets.minioPassword}`,
    "OBJECT_STORAGE_REGION=us-east-1",
    "OBJECT_STORAGE_TLS_POLICY=required",
    "OBJECT_STORAGE_PATH_STYLE=true",
    "OBJECT_STORAGE_HEALTH_PREFIX=.health/",
    "OBJECT_STORAGE_RETENTION_CLASS=pilot-default",
    "",
    "BACKUP_DATABASE_TARGET=file:///var/backups/wiseeff/postgres/wiseeff.dump",
    "BACKUP_OBJECT_STORAGE_TARGET=file:///var/backups/wiseeff/object-store/",
    "RESTORE_DATABASE_URL=postgres://wiseeff_restore:restore-password@postgres:5432/wiseeff_restore",
    "RESTORE_OBJECT_STORAGE_BUCKET=wiseeff-restore",
    "RESTORE_OBJECT_STORAGE_PREFIX=m6-drill/",
    "",
    "DEBUG_DEVICE_GATEWAY_MODE=multi",
    "DEVICE_GATEWAY_ALLOW_SIMULATOR_IN_PRODUCTION=true",
    "HDC_TIMEOUT_MS=5000",
    "ADB_TIMEOUT_MS=5000",
    "",
    "DEVICE_BRIDGE_ARTIFACT_ROOT=ops/self-hosted/bridge-artifacts",
    "DEVICE_BRIDGE_TOOL_ARTIFACT_ROOT=ops/self-hosted/bridge-tool-artifacts",
    "DEVICE_BRIDGE_PAIRING_TTL_SECONDS=1800",
    "DEVICE_BRIDGE_TOKEN_TTL_DAYS=90",
    "DEVICE_BRIDGE_WS_PATH=/api/v1/device-bridges/ws",
    "DEVICE_BRIDGE_LAB_AVAILABLE=false",
    `DEVICE_BRIDGE_SERVER_URL=${publicUrl}`,
    "",
    `AGENT_API_BASE_URL=${answers.agentApiBaseUrl}`,
    `AGENT_MODEL=${answers.agentModel}`,
    `AGENT_API_KEY=${answers.agentApiKey}`,
    "AGENT_API_TIMEOUT_MS=30000",
    "XIAOZE_CHECKPOINTER=postgres",
    `XIAOZE_DETERMINISTIC=${xiaozeDeterministic}`,
    "",
    `LOG_ANALYSIS_API_BASE_URL=${answers.logAnalysisApiBaseUrl}`,
    `LOG_ANALYSIS_MODEL=${answers.logAnalysisModel}`,
    `LOG_ANALYSIS_API_KEY=${answers.logAnalysisApiKey}`,
    "LOG_ANALYSIS_API_TIMEOUT_MS=30000",
    "LOG_ANALYSIS_TOKEN_BUDGET=8000",
    `LOG_ANALYSIS_DETERMINISTIC=${logAnalysisDeterministic}`,
    "",
    "LOG_WORKER_ENABLED=false",
    "LOG_ANALYSIS_QUEUE_MODE=durable",
    "REDIS_URL=redis://redis:6379",
    "LOG_ANALYSIS_QUEUE_PREFIX=wiseeff",
    "LOG_ANALYSIS_QUEUE_ATTEMPTS=4",
    "LOG_ANALYSIS_QUEUE_BACKOFF_MS=1000",
    "LOG_ANALYSIS_QUEUE_CONCURRENCY=1",
    "LOG_WORKER_OBSERVABILITY_HOST=127.0.0.1",
    "LOG_WORKER_OBSERVABILITY_PORT=8788",
    "",
    "WISEEFF_GRAFANA_PORT=3000",
    "WISEEFF_PROMETHEUS_PORT=9090",
    "WISEEFF_ALERTMANAGER_PORT=9093",
    "WISEEFF_PROMETHEUS_RETENTION=15d",
    "",
    "M5_CONTRACT_CHECK_PASSED=true",
    "M5_BACKUP_RESTORE_DRILL_AT=",
    "M5_SMOKE_ALLOW_NO_API=false",
    ""
  ].join("\n");
}

export function evaluateSelfHostEnv(env: Record<string, string | undefined>): IpLabPreflightResult {
  const profile = (env.WISEEFF_DEPLOY_PROFILE ?? "").trim();
  if (profile === acmeDeployProfile) {
    return evaluateAcmeEnv(env);
  }
  return evaluateIpLabEnv(env);
}

function evaluateAcmeEnv(env: Record<string, string | undefined>): IpLabPreflightResult {
  const issues: IpLabPreflightResult["issues"] = [];
  const requireValue = (key: string) => {
    const value = env[key]?.trim();
    if (!value) {
      issues.push({ level: "error", message: `${key} is required for the ACME profile.` });
    }
    return value;
  };

  if ((env.WISEEFF_DEPLOY_PROFILE ?? "").trim() !== acmeDeployProfile) {
    issues.push({ level: "error", message: "WISEEFF_DEPLOY_PROFILE must be acme." });
  }
  if ((env.WISEEFF_TLS_MODE ?? "").trim() !== "acme") {
    issues.push({ level: "error", message: "WISEEFF_TLS_MODE must be acme." });
  }
  if ((env.WISEEFF_CADDYFILE ?? "").trim() !== acmeCaddyfile) {
    issues.push({ level: "error", message: `WISEEFF_CADDYFILE must be ${acmeCaddyfile}.` });
  }
  if ((env.NODE_ENV ?? "").trim() !== "production") {
    issues.push({ level: "error", message: "NODE_ENV must be production." });
  }
  if ((env.AUTH_PROVIDER ?? "").trim() !== "local") {
    issues.push({
      level: "error",
      message: "AUTH_PROVIDER must be local for wizard-managed ACME v1. OIDC is out of this wizard."
    });
  }

  const host = requireValue("WISEEFF_SITE_HOST");
  const email = requireValue("WISEEFF_TLS_EMAIL");
  if (email && !email.includes("@")) {
    issues.push({ level: "error", message: "WISEEFF_TLS_EMAIL must be an email address." });
  }
  const publicUrl = requireValue("WISEEFF_PUBLIC_URL");
  if (host && publicUrl) {
    const expected = publicUrlForSelfHost(host, "acme");
    if (publicUrl !== expected) {
      issues.push({
        level: "error",
        message: `WISEEFF_PUBLIC_URL must be ${expected} for host ${host}.`
      });
    }
  }
  for (const key of ["WISEEFF_API_BASE_URL", "VITE_WISEEFF_API_BASE_URL", "DEVICE_BRIDGE_SERVER_URL"] as const) {
    const value = env[key]?.trim();
    if (publicUrl && value && value !== publicUrl) {
      issues.push({ level: "error", message: `${key} must match WISEEFF_PUBLIC_URL.` });
    }
  }

  const postgresPassword = requireValue("POSTGRES_PASSWORD");
  if (postgresPassword && !urlSafeSecretPattern.test(postgresPassword)) {
    issues.push({
      level: "error",
      message: "POSTGRES_PASSWORD must be URL-safe ([A-Za-z0-9_-]) so DATABASE_URL stays valid."
    });
  }
  const databaseUrl = requireValue("DATABASE_URL");
  if (databaseUrl?.includes("${")) {
    issues.push({ level: "error", message: "DATABASE_URL must embed the expanded POSTGRES_PASSWORD." });
  } else if (postgresPassword && databaseUrl && !databaseUrl.includes(postgresPassword)) {
    issues.push({ level: "error", message: "DATABASE_URL must embed the expanded POSTGRES_PASSWORD." });
  }

  requireValue("WISEEFF_LAB_ADMIN_USERNAME");
  const adminPassword = requireValue("WISEEFF_LAB_ADMIN_PASSWORD");
  if (adminPassword && adminPassword.length < 8) {
    issues.push({ level: "error", message: "WISEEFF_LAB_ADMIN_PASSWORD must be at least 8 characters." });
  }

  const xiaozeReady =
    (env.XIAOZE_DETERMINISTIC ?? "").trim() === "true" ||
    Boolean(env.AGENT_API_BASE_URL?.trim() && env.AGENT_API_KEY?.trim());
  if (!xiaozeReady) {
    issues.push({
      level: "error",
      message: "Set XIAOZE_DETERMINISTIC=true or provide AGENT_API_BASE_URL and AGENT_API_KEY."
    });
  }
  const logAnalysisReady =
    (env.LOG_ANALYSIS_DETERMINISTIC ?? "").trim() === "true" ||
    Boolean(env.LOG_ANALYSIS_API_BASE_URL?.trim() && env.LOG_ANALYSIS_API_KEY?.trim());
  if (!logAnalysisReady) {
    issues.push({
      level: "error",
      message:
        "Set LOG_ANALYSIS_DETERMINISTIC=true or provide LOG_ANALYSIS_API_BASE_URL and LOG_ANALYSIS_API_KEY."
    });
  }

  if ((env.LOG_ANALYSIS_QUEUE_MODE ?? "").trim() !== "durable") {
    issues.push({ level: "error", message: "LOG_ANALYSIS_QUEUE_MODE must be durable." });
  }
  requireValue("REDIS_URL");

  return {
    status: issues.some((issue) => issue.level === "error") ? "failed" : "passed",
    issues
  };
}

export function evaluateSelfHostCaddyfile(text: string, tlsMode: SelfHostTlsMode) {
  if (tlsMode === "acme") {
    const normalized = text.replace(/\r\n/g, "\n").replace(/[ \t]+/g, " ").trim();
    const missingTokens = requiredAcmeCaddyTokens.filter((token) => !normalized.includes(token));
    return {
      status: missingTokens.length === 0 ? "passed" : "failed",
      missingTokens,
      forbiddenTokens: [] as string[]
    };
  }
  return evaluateIpLabCaddyfile(text, tlsMode);
}

export function summarizeEnv(env: Record<string, string | undefined>) {
  return {
    profile: env.WISEEFF_DEPLOY_PROFILE?.trim() || "unknown",
    tlsMode: env.WISEEFF_TLS_MODE?.trim() || "",
    publicUrl: env.WISEEFF_PUBLIC_URL?.trim() || "",
    adminUsername: env.WISEEFF_LAB_ADMIN_USERNAME?.trim() || "",
    seed: env.WISEEFF_LAB_SEED?.trim() || "chargelab",
    llm:
      env.AGENT_API_KEY?.trim() && env.LOG_ANALYSIS_API_KEY?.trim()
        ? "xiaoze+logs"
        : env.AGENT_API_KEY?.trim()
          ? "xiaoze"
          : "skip"
  };
}

export { parseEnvText };
