/**
 * User-facing Chinese copy for parameter admin / governance surfaces.
 * Keep code identifiers (spec, binding, …); only UI strings live here.
 */

export const PARAMETER_ADMIN_UI = {
  orgScope: "组织配置",
  projectScope: "项目运营",
  orgSubnavAria: "组织配置子视图",
  scopeNavAria: "参数管理后台配置范围",

  /** Organization peer nav label (ADR-0015). In-page library title stays `specLibrary`. */
  specDefinitionManagement: "参数定义管理",
  specLibrary: "参数定义库",
  specLibrarySearch: "搜索参数定义",
  specLibraryEmpty: "没有匹配的参数定义。",
  specLibraryLoading: "正在加载参数定义…",
  specLibraryBlurb:
    "按属性键维护可复用的参数定义；所属模块来自项目绑定实测，未观测时显示为未实测。",
  specDetail: "参数定义详情",
  specDetailEyebrowEditable: "参数定义库 · 可编辑",
  specDetailEyebrowReadonly: "参数定义库 · 只读",
  specKey: "定义标识",
  specDocs: "参数说明",
  activateSpec: "激活定义",
  activateDraftSpec: "激活草稿定义",
  createDraftSpec: "创建草稿定义",
  saveAndActivate: "保存并激活",

  specReview: "定义匹配审核",
  specReviewQueue: "定义匹配审核队列",
  specReviewQueueBlurb:
    "导入 DTS 后，系统没能自动对上参数定义的属性会出现在这里。打开任务选定定义并批准即可；库里没有时，先新建并启用定义，再回来批准。",
  specReviewEmpty: "没有待确认的自动匹配。",
  specReviewNoFilterMatch: "没有匹配的审核任务。",
  specReviewDialogEyebrow: "定义匹配审核 · 审核决定",
  specReviewEvidence: "匹配依据",
  specReviewCandidates: "系统推荐定义",
  specReviewDecision: "审核决定",
  specReviewQueueToggle: "定义匹配审核队列",
  searchSpecLibrary: "搜索参数定义库",
  selectSpec: "选择参数定义",
  selectSpecPlaceholder: "请选择参数定义…",
  searchSpecPlaceholder: "按属性键、驱动或定义标识搜索",
  approveReasonPlaceholder: "说明为何选择该参数定义",
  specReviewApproved: "定义匹配审核已批准。",
  specReviewDismissed: "定义匹配审核已驳回。",
  specReviewApprovedAudit: "定义匹配审核已批准",
  specReviewDismissedAudit: "定义匹配审核已驳回",

  matchUnmatched: "未找到定义",
  matchAmbiguous: "匹配冲突",
  matchHasCandidates: "有多项匹配",

  /** Organization peer nav label (ADR-0015). In-page tree title stays `moduleMappingManage`. */
  moduleManagement: "模块管理",
  moduleMapping: "模块归属",
  moduleMappingManage: "模块归属",
  moduleMappingBlurb: "业务分类 → 驱动组 / 节点类型。在树里维护已归属模块；器件实例由工作台器件层浏览。",
  moduleTreeTitle: "模块树",
  moduleTreeSubnav: "归属树",
  moduleDiscoveryCompatible: "未登记驱动",
  moduleDiscoveryCompatibleEmpty: "当前没有未登记的驱动。",
  moduleQueueSubnavAria: "模块管理子视图",
  moduleQueueBanner: "有未登记的驱动",
  moduleQueueBannerAction: "去处理未登记驱动",
  specsSubnavAria: "参数定义管理子视图",
  specsLibrarySubnav: "定义库",
  identityMappingCountError: "节点对应任务计数加载失败",
  classifyCompatible: "归类",
  classifyCompatibleBulk: "批量归类",
  dismissCompatible: "忽略",
  restoreCompatible: "恢复忽略",
  classifyDialogEyebrow: "模块归属 · 归类 compatible",
  classifyDialogTitle: "归类到业务分类",
  classifyDialogBulkTitle: "批量归类到业务分类",
  classifyTargetBusiness: "目标业务分类",
  classifyDriverGroupName: "驱动组名称",
  classifyPreview: "影响预览",
  classifyApply: "确认归类",
  classifyBlocked: "存在阻断冲突，无法归类",
  driverRegistryRegisterDialogTitle: "登记驱动",
  driverRegistryRegister: "登记驱动",
  claimDriver: "认领登记",
  driverRegistryDisplayName: "显示名称",
  driverRegistryBusinessCategory: "业务分类",
  driverRegistryCompatibles: "compatible（每行一条）",
  driverRegistryNotes: "备注",
  driverRegistryNotYetObserved: "未实测",
  driverRegistryCoverageCovered: "官方解析覆盖",
  driverRegistryCoverageOverlay: "组织级解析覆盖",
  driverRegistryCoverageShadowed: "被更高优先级覆盖",
  driverRegistryCoveragePromoted: "官方解析覆盖",
  driverRegistryCoveragePlatform: "平台级解析覆盖",
  driverRegistryCoverageUncovered: "解析未覆盖",
  driverRegistryDefaultBusinessCategory: "默认业务分类",
  driverRegistryDefaultBusinessCategoryHint:
    "自动发现的驱动组跟随此默认分类；人工 curated 放置保持冻结，不会随默认变更移动。",
  driverRegistryReplayPlacement: "从注册回放放置",
  driverRegistryReplayPlacementHint:
    "仅移动 origin=auto 的驱动组到注册默认业务分类；curated 跳过。",
  driverRegistryReplayPlacementDone: "回放完成",
  moduleAttributionHideNotYetObserved: "隐藏未实测",
  moduleAttributionOnlyUncoveredParse: "仅显示解析未覆盖",
  moduleAttributionCoveragePartial: "解析覆盖 {covered}/{total}",
  moduleAttributionCoverageCovered: "官方解析覆盖",
  moduleAttributionCoverageOverlay: "组织级解析覆盖",
  moduleAttributionCoveragePlatform: "平台级解析覆盖",
  moduleAttributionCoveragePromoted: "官方解析覆盖",
  moduleAttributionCoverageShadowed: "被更高优先级覆盖",
  moduleAttributionCoverageUncovered: "解析未覆盖",
  authorOverlaySchema: "配置组织级解析",
  organizationDriverSchemaDialogTitle: "配置组织级解析",
  organizationDriverSchemaDisplayName: "显示名称",
  organizationDriverSchemaNotes: "备注",
  organizationDriverSchemaProperties: "关联参数定义",
  organizationDriverSchemaPropertyKey: "属性键",
  organizationDriverSchemaValueShape: "值类型",
  organizationDriverSchemaUnits: "单位",
  organizationDriverSchemaDocumentation: "说明",
  organizationDriverSchemaAddProperty: "添加参数定义",
  organizationDriverSchemaSaveActivate: "保存并激活",
  organizationDriverSchemaEmptyLinks: "尚未关联参数定义。点击下方按钮从定义库选用或新建。",
  organizationDriverSchemaPendingCreate: "保存时写入定义库",
  organizationDriverSchemaRemoveLink: "移除",
  organizationDriverSchemaPickerTitle: "选择参数定义",
  organizationDriverSchemaPickerBlurb:
    "点击表格行或「选用」选中一条定义，再点「使用所选」带回；也可新建定义。",
  organizationDriverSchemaPickerConfirm: "使用所选",
  organizationDriverSchemaPickerBack: "返回",
  organizationDriverSchemaCreateTitle: "新建参数定义",
  organizationDriverSchemaCreateConfirm: "创建并选用",
  organizationDriverSchemaLinkExisting: "选用已有定义",
  organizationDriverSchemaCreateNew: "新建定义",
  organizationDriverSchemaSelectSpec: "参数定义",
  organizationDriverSchemaMode: "来源",
  organizationDriverSchemaPlatformBlocked:
    "该驱动已存在平台级解析覆盖，无法再配置组织级解析。",
  organizationDriverSchemaLifecycle: "生命周期",
  organizationDriverSchemaDeprecate: "停用解析",
  organizationDriverSchemaDeprecateConfirm:
    "确定停用解析「{name}」（compatible {compatible}）？\n停用后该 compatible 的组织级解析覆盖将撤回，相关参数可能变为解析未覆盖。",
  organizationDriverSchemaOverlays: "组织级解析",
  organizationDriverSchemaOverlaysEmpty: "尚未配置组织级解析。",
  moduleAttributionMoveUp: "上移",
  moduleAttributionMoveDown: "下移",
  dismissedCompatibleSection: "已忽略",
  queueColCompatible: "compatible",
  queueColBindings: "影响参数",
  queueColProjects: "涉及项目",
  queueColSuggested: "建议驱动组",
  queueColActions: "操作",
  specAttributionModule: "所属模块",

  identityMapping: "节点对应确认",
  identityMappingGovernance: "节点对应确认",
  identityMappingBlurb: "确认迁移期未能自动对齐的参数节点对应关系。",
  identityMappingEmpty: "当前没有待处理的节点对应任务。",
  identityMappingLoading: "正在加载节点对应任务…",
  identityMappingLoadError: "无法加载节点对应任务。",
  identityMappingResolveError: "节点对应确认失败。",
  identityMappingReview: "节点对应审核",
  identityMappingCandidates: "候选拓扑节点",
  selectIdentityCandidate: "选择对应节点",
  confirmIdentityMapping: "确认对应",
  currentIdentityMapping: "当前对应",
  reselectIdentityCandidate: "重新选择对应节点",
  identityReResolveReason: "重新对应原因",
  identityReResolveReasonPlaceholder: "说明为何更正已应用的节点对应",
  confirmIdentityReResolve: "确认重新对应",
  identityReResolveGuidance:
    "已对应任务不可重开；如原决定有误，可在没有下游草稿、提交或设备操作时受保护地更正。",
  identityReResolveMigrationRequired:
    "当前任务缺少安全更正所需的连续性证据；请通过显式迁移或上传新 DTS 处理。",
  identityReResolveSelectDifferent: "请选择不同于当前对应的候选节点",
  identityReResolveReasonRequired: "请填写重新对应原因",
  identityReResolveSubmitting: "正在提交重新对应",
  declareNewIdentity: "声明新身份",
  identityMappingTaskKindAmbiguity: "身份歧义",
  identityMappingTaskKindSingleton: "单例冲突",
  identityMappingConfirmAllCandidates: "确认保留全部候选为新身份",
  identityMappingSingletonGuidanceLabel: "单例冲突修复指引",
  identityMappingSingletonGuidance:
    "该任务为单例冲突：驱动登记要求每个项目仅保留一个实例。请在驱动登记或项目拓扑中移除多余实例或更正 instanceCardinality，无法通过节点对应决议消除。开放任务仍会阻断发布校验。",
  identityConfirmReason: "确认原因",
  identityConfirmReasonPlaceholder: "说明为何选择该节点",

  changeReview: "变更审阅",
  adminSubtitle:
    "组织配置与项目运营；子路由涵盖参数定义管理、模块管理与批量导入",

  xiaozeSpecReview: "正在关注定义匹配审核队列与类型定义确认。",
  xiaozeIdentityMapping: "正在关注迁移期节点对应任务与无损确认。",
  xiaozeOrgDefault:
    "正在关注组织级参数定义管理、模块管理、批量导入与节点对应确认。",

  lifecycleDraft: "草稿",
  lifecycleActive: "已启用",
  lifecycleDeprecated: "已废弃",
  deprecateSpec: "废弃",
  restoreSpec: "恢复",
  deprecateReasonPlaceholder: "说明废弃原因（必填）",
  restoreReasonPlaceholder: "说明恢复原因（必填）",
  deprecateImpact: "废弃后仍参与解析，但不再出现在定义库默认视图，也不能被审核任务选中。",
  definitionCountLabel: "定义数",
  occurrenceCountLabel: "实测处数",
  referenceCountLabel: "引用数",
  referenceCountAsOccurrence: "该定义的实测处数",
  showDeprecatedHint: "默认隐藏已废弃定义；在审核状态筛选中勾选「已废弃」可查看。",
  propertyKeyCutoverTitle: "属性键切换",
  propertyKeyCutoverHint:
    "有引用时不能行内改键。先预检，再把源改写暂存为文件草稿；人在配置工作台合入现行源之后，才能完成切换。",
  propertyKeyCutoverNextKey: "新属性键",
  propertyKeyCutoverReason: "原因",
  propertyKeyCutoverPreview: "预检",
  propertyKeyCutoverStart: "启动作业",
  propertyKeyCutoverPrepare: "暂存草稿",
  propertyKeyCutoverFinalize: "完成切换",
  propertyKeyCutoverStaged: "已暂存文件草稿，现行源尚未改写。请在配置工作台审阅并合入后再完成切换。",
  propertyKeyCutoverHandoffActivatedHint: "文件草稿已合入现行源。请再预检，确认源已是新键后再完成切换。",
  propertyKeyCutoverHandoffAbandonedHint: "文件草稿已放弃。请重新暂存草稿，或处理不兼容项。",
  propertyKeyCutoverHandoffReadyHint: "源已是新键，可以完成切换。",
  propertyKeyCutoverHandoffUnnamedLink: "在配置工作台审阅并合入该文件草稿",
  propertyKeyCutoverHandoffUnnamedViewLink: "在配置工作台查看该文件草稿",
  propertyKeyCutoverCandidateStaged: "已暂存",
  propertyKeyCutoverCandidateActivated: "已合入现行源",
  propertyKeyCutoverCandidateAbandoned: "已放弃",
  propertyKeyCutoverCandidateStale: "候选已过期",
  propertyKeyCutoverCandidateBlocked: "候选被阻断",
  propertyKeyCutoverCandidateFailed: "候选失败",
  propertyKeyCutoverCandidateMissing: "候选已不可用",
  propertyKeyCutoverRefreshStatus: "刷新候选状态",
  propertyKeyCutoverUnnamedFile: "未命名文件",
  propertyKeyCutoverUnknownStatus: "待处理",
  propertyKeyCutoverResumeFailed: "无法读取进行中的属性键切换，请重试。",
} as const;

export type SpecReviewMatchStatusUi =
  | typeof PARAMETER_ADMIN_UI.matchUnmatched
  | typeof PARAMETER_ADMIN_UI.matchAmbiguous
  | typeof PARAMETER_ADMIN_UI.matchHasCandidates;

/** Localize lifecycle enums for display; keep raw value as fallback. */
export function formatParameterSpecLifecycle(raw: string | null | undefined): string {
  switch ((raw ?? "").trim()) {
    case "draft":
      return PARAMETER_ADMIN_UI.lifecycleDraft;
    case "active":
      return PARAMETER_ADMIN_UI.lifecycleActive;
    case "deprecated":
      return PARAMETER_ADMIN_UI.lifecycleDeprecated;
    default:
      return raw?.trim() || "—";
  }
}
