export type BilingualDocStatus = "required" | "deferred";

export interface BilingualDocEntry {
  en: string;
  zh: string;
  tier: string;
  status: BilingualDocStatus;
}

export const developerFacingBilingualDocs: BilingualDocEntry[] = [
  { en: "AGENTS.md", zh: "docs/zh-CN/root/AGENTS.md", tier: "core", status: "required" },
  { en: "README.md", zh: "docs/zh-CN/root/README.md", tier: "core", status: "required" },
  { en: "CONTRIBUTING.md", zh: "docs/zh-CN/root/CONTRIBUTING.md", tier: "core", status: "required" },
  { en: "ARCHITECTURE.md", zh: "docs/zh-CN/root/ARCHITECTURE.md", tier: "core", status: "required" },
  { en: "docs/README.md", zh: "docs/zh-CN/README.md", tier: "core", status: "required" },
  { en: "docs/FRONTEND.md", zh: "docs/zh-CN/frontend.md", tier: "core", status: "required" },
  { en: "docs/PLANS.md", zh: "docs/zh-CN/PLANS.md", tier: "core", status: "required" },
  { en: "docs/QUALITY_SCORE.md", zh: "docs/zh-CN/QUALITY_SCORE.md", tier: "core", status: "required" },
  { en: "docs/RELIABILITY.md", zh: "docs/zh-CN/RELIABILITY.md", tier: "core", status: "required" },
  { en: "docs/SECURITY.md", zh: "docs/zh-CN/SECURITY.md", tier: "core", status: "required" },
  { en: "docs/developer/README.md", zh: "docs/zh-CN/developer/README.md", tier: "developer", status: "required" },
  { en: "docs/developer/local-development.md", zh: "docs/zh-CN/developer/local-development.md", tier: "developer", status: "required" },
  { en: "docs/developer/environment-variables.md", zh: "docs/zh-CN/developer/environment-variables.md", tier: "developer", status: "required" },
  { en: "docs/developer/verification-matrix.md", zh: "docs/zh-CN/developer/verification-matrix.md", tier: "developer", status: "required" },
  { en: "docs/developer/user-operation-coverage-matrix.md", zh: "docs/zh-CN/developer/user-operation-coverage-matrix.md", tier: "developer", status: "required" },
  { en: "docs/developer/browser-acceptance-coverage-map.md", zh: "docs/zh-CN/developer/browser-acceptance-coverage-map.md", tier: "developer", status: "required" },
  { en: "docs/product-specs/index.md", zh: "docs/zh-CN/product-specs/index.md", tier: "product", status: "required" },
  { en: "docs/product-specs/product-spec.md", zh: "docs/zh-CN/product-specs/product-spec.md", tier: "product", status: "required" },
  { en: "docs/product-specs/prototype-functional-spec.md", zh: "docs/zh-CN/product-specs/prototype-functional-spec.md", tier: "product", status: "required" },
  { en: "docs/product-specs/mvp-scope.md", zh: "docs/zh-CN/product-specs/mvp-scope.md", tier: "product", status: "required" },
  { en: "docs/product-specs/new-user-onboarding.md", zh: "docs/zh-CN/product-specs/new-user-onboarding.md", tier: "product", status: "required" },
  { en: "docs/design-docs/index.md", zh: "docs/zh-CN/design-docs/index.md", tier: "architecture", status: "required" },
  { en: "docs/design-docs/core-beliefs.md", zh: "docs/zh-CN/design-docs/core-beliefs.md", tier: "architecture", status: "required" },
  { en: "docs/design-docs/full-stack-architecture.md", zh: "docs/zh-CN/design-docs/full-stack-architecture.md", tier: "architecture", status: "required" },
  { en: "docs/design-docs/domain-model.md", zh: "docs/zh-CN/design-docs/domain-model.md", tier: "architecture", status: "required" },
  { en: "docs/design-docs/api-contract.md", zh: "docs/zh-CN/design-docs/api-contract.md", tier: "architecture", status: "required" },
  { en: "docs/design-docs/testing-strategy.md", zh: "docs/zh-CN/design-docs/testing-strategy.md", tier: "architecture", status: "required" },
  { en: "docs/design-docs/deployment-operations.md", zh: "docs/zh-CN/design-docs/deployment-operations.md", tier: "architecture", status: "required" },
  { en: "docs/design-docs/security-governance.md", zh: "docs/zh-CN/design-docs/security-governance.md", tier: "architecture", status: "required" },
  { en: "docs/api/README.md", zh: "docs/zh-CN/api/README.md", tier: "api", status: "required" },
  { en: "docs/api/authentication.md", zh: "docs/zh-CN/api/authentication.md", tier: "api", status: "required" },
  { en: "docs/api/errors.md", zh: "docs/zh-CN/api/errors.md", tier: "api", status: "required" },
  { en: "docs/api/examples.md", zh: "docs/zh-CN/api/examples.md", tier: "api", status: "required" },
  { en: "docs/security/README.md", zh: "docs/zh-CN/security/README.md", tier: "security", status: "required" },
  { en: "docs/security/threat-model.md", zh: "docs/zh-CN/security/threat-model.md", tier: "security", status: "required" },
  { en: "docs/security/data-classification.md", zh: "docs/zh-CN/security/data-classification.md", tier: "security", status: "required" },
  { en: "docs/security/secrets-management.md", zh: "docs/zh-CN/security/secrets-management.md", tier: "security", status: "required" },
  { en: "docs/security/audit-retention.md", zh: "docs/zh-CN/security/audit-retention.md", tier: "security", status: "required" },
  { en: "docs/security/user-permission-design.md", zh: "docs/zh-CN/security/user-permission-design.md", tier: "security", status: "required" },
  { en: "docs/runbooks/README.md", zh: "docs/zh-CN/runbooks/README.md", tier: "runbook", status: "required" },
  { en: "docs/runbooks/manual-acceptance.md", zh: "docs/zh-CN/runbooks/manual-acceptance.md", tier: "runbook", status: "required" },
  { en: "docs/runbooks/m5-commercial-pilot-readiness.md", zh: "docs/zh-CN/runbooks/m5-commercial-pilot-readiness.md", tier: "runbook", status: "required" },
  { en: "docs/runbooks/self-hosted-runtime.md", zh: "docs/zh-CN/runbooks/self-hosted-runtime.md", tier: "runbook", status: "required" },
  { en: "docs/runbooks/identity-provider.md", zh: "docs/zh-CN/runbooks/identity-provider.md", tier: "runbook", status: "required" },
  { en: "docs/runbooks/durable-queue.md", zh: "docs/zh-CN/runbooks/durable-queue.md", tier: "runbook", status: "required" },
  { en: "docs/runbooks/staging-deployment.md", zh: "docs/zh-CN/runbooks/staging-deployment.md", tier: "runbook", status: "required" },
  { en: "docs/runbooks/backup-restore.md", zh: "docs/zh-CN/runbooks/backup-restore.md", tier: "runbook", status: "required" },
  { en: "docs/runbooks/rollback.md", zh: "docs/zh-CN/runbooks/rollback.md", tier: "runbook", status: "required" },
  { en: "docs/runbooks/release-rollback.md", zh: "docs/zh-CN/runbooks/release-rollback.md", tier: "runbook", status: "required" },
  { en: "docs/runbooks/monitoring-alerting.md", zh: "docs/zh-CN/runbooks/monitoring-alerting.md", tier: "runbook", status: "required" },
  { en: "docs/runbooks/observability-operations.md", zh: "docs/zh-CN/runbooks/observability-operations.md", tier: "runbook", status: "required" },
  { en: "docs/runbooks/incidents.md", zh: "docs/zh-CN/runbooks/incidents.md", tier: "runbook", status: "required" },
  { en: "docs/runbooks/hdc-device-lab.md", zh: "docs/zh-CN/runbooks/hdc-device-lab.md", tier: "runbook", status: "required" },
  { en: "docs/runbooks/agent-provider.md", zh: "docs/zh-CN/runbooks/agent-provider.md", tier: "runbook", status: "required" },
  { en: "docs/runbooks/wsl-linux-validation.md", zh: "docs/zh-CN/wsl-linux-validation.md", tier: "runbook", status: "required" },
  { en: "ops/self-hosted/README.md", zh: "ops/self-hosted/README.zh-CN.md", tier: "self-hosted", status: "required" },
  { en: "ops/self-hosted/storage/README.md", zh: "ops/self-hosted/storage/README.zh-CN.md", tier: "self-hosted", status: "required" },
  { en: "ops/self-hosted/storage/provider-decision.md", zh: "ops/self-hosted/storage/provider-decision.zh-CN.md", tier: "self-hosted", status: "required" },
  { en: "ops/self-hosted/releases/README.md", zh: "ops/self-hosted/releases/README.zh-CN.md", tier: "self-hosted", status: "required" },
  { en: "ops/self-hosted/releases/release-template.md", zh: "ops/self-hosted/releases/release-template.zh-CN.md", tier: "self-hosted", status: "required" },
  { en: "docs/exec-plans/active/development-roadmap.md", zh: "docs/zh-CN/exec-plans/development-roadmap.md", tier: "planning", status: "required" },
  { en: "docs/exec-plans/tech-debt-tracker.md", zh: "docs/zh-CN/exec-plans/tech-debt-tracker.md", tier: "planning", status: "required" }
];
