import { describe, expect, it } from "vitest";
import { initialState } from "./mockData";
import {
  buildReviewDetailSummary,
  complexEditorRows,
  getParameterValueSummary,
  isAutoGeneratedChangeSummary,
  isComplexParameter,
  isComplexParameterValue,
  isRedundantReviewSummary,
  shouldShowReviewDetailReason,
  shouldSummarizeComplexParameter,
  shouldSummarizeReviewChange
} from "./parameterValueKind";

describe("parameterValueKind", () => {
  it("uses valueKind to detect complex parameters", () => {
    const scalar = initialState.configDraft.parameterLibrary.find((parameter) => parameter.name === "fast_charge_current_limit_ma");
    const complex = initialState.configDraft.parameterLibrary.find((parameter) => parameter.name === "battery_thermal_derate_curve");

    expect(scalar).toBeDefined();
    expect(complex).toBeDefined();
    expect(scalar!.valueKind).toBe("scalar");
    expect(complex!.valueKind).toBe("complex");
    expect(isComplexParameter(scalar!)).toBe(false);
    expect(isComplexParameter(complex!)).toBe(true);
  });

  it("falls back to multiline content when valueKind is missing", () => {
    const multiline = "battery-thermal-derate-curve = <\n  0 38 3800 4350\n>;";
    expect(isComplexParameterValue(multiline)).toBe(true);
    expect(shouldSummarizeComplexParameter({ valueKind: "scalar" }, multiline)).toBe(true);
    expect(getParameterValueSummary(multiline).propertyName).toBe("battery-thermal-derate-curve");
  });

  it("caps complex editor row height", () => {
    expect(complexEditorRows("one\ntwo\nthree")).toBe(6);
    expect(complexEditorRows(Array.from({ length: 20 }, (_, index) => `line-${index}`).join("\n"))).toBe(16);
  });

  it("summarizes review changes from parameter metadata or long single-line values", () => {
    const complex = initialState.configDraft.parameterLibrary.find((parameter) => parameter.name === "battery_thermal_derate_curve");
    expect(complex).toBeDefined();

    const flattenedValue =
      "battery-thermal-derate-curve = < 0 38 3800 4350 1 42 3200 4320 2 45 2600 4280 >;";
    const flattenedTarget =
      "battery-thermal-derate-curve = < 0 38 3800 4350 1 42 3200 4320 2 45 2600 4380 >;";

    expect(
      shouldSummarizeReviewChange(
        { currentValue: flattenedValue, targetValue: flattenedTarget },
        { valueKind: complex!.valueKind, configFormat: complex!.configFormat }
      )
    ).toBe(true);
    expect(
      shouldSummarizeReviewChange({ currentValue: flattenedValue, targetValue: flattenedTarget })
    ).toBe(true);
    expect(
      shouldSummarizeReviewChange({ currentValue: "15", targetValue: "13" })
    ).toBe(false);
  });

  it("builds readable review detail summaries and detects auto-generated dumps", () => {
    const complex = initialState.configDraft.parameterLibrary.find((parameter) => parameter.name === "battery_thermal_derate_curve");
    expect(complex).toBeDefined();

    const complexSummary = buildReviewDetailSummary({
      title: complex!.name,
      currentValue: complex!.values.aurora.currentValue,
      targetValue: complex!.values.aurora.currentValue.replace("4280", "4380"),
      valueKind: complex!.valueKind,
      configFormat: complex!.configFormat
    });

    expect(complexSummary.isComplex).toBe(true);
    expect(complexSummary.headline).toContain("battery_thermal_derate_curve");
    expect(complexSummary.headline).toContain("复杂配置");
    expect(complexSummary.hasDifference).toBe(true);

    const scalarSummary = buildReviewDetailSummary({
      title: "standby_drain_limit_ma",
      currentValue: "18",
      targetValue: "15"
    });

    expect(scalarSummary.isComplex).toBe(false);
    expect(scalarSummary.headline).toBe("将 standby_drain_limit_ma 从 18 调整为 15。");
    expect(isAutoGeneratedChangeSummary("battery_thermal_derate_curve changes from old to new.")).toBe(true);
    expect(isAutoGeneratedChangeSummary("建议推进：将快充电流从 3800mA 回落到 3200mA。")).toBe(false);
    expect(isRedundantReviewSummary("battery_thermal_derate_curve 为复杂配置（5 行），当前与目标不同。")).toBe(true);
    expect(shouldShowReviewDetailReason("Risk level: Low")).toBe(false);
    expect(shouldShowReviewDetailReason("历史相似 3 条全部成功合入")).toBe(true);
  });
});
