import type { ParameterValueKind } from "./powerManagementConfig";

export type { ParameterValueKind };

export function isComplexParameterValue(value: string) {
  const normalized = value.trim();
  return normalized.includes("\n") || normalized.length >= 80;
}

export function isComplexParameter(parameter: { valueKind?: ParameterValueKind }) {
  return parameter.valueKind === "complex";
}

export function shouldSummarizeComplexParameter(
  parameter: { valueKind?: ParameterValueKind; configFormat?: string },
  ...values: string[]
) {
  if (parameter.valueKind === "complex") {
    return true;
  }

  const format = parameter.configFormat?.trim() ?? "";
  if (format.startsWith("DTS:") || format.includes("string-list")) {
    return true;
  }

  return values.some((value) => {
    const normalized = value.trim();
    return normalized.length > 0 && isComplexParameterValue(normalized);
  });
}

export function getParameterValueSummary(value: string) {
  const firstLine = value.split("\n")[0]?.trim() ?? "";
  const propertyName = firstLine.replace(/\s*=.*$/, "").trim() || "配置块";
  const lineCount = value.split("\n").filter((line) => line.trim()).length;
  return { propertyName, lineCount };
}

export function shouldSummarizeReviewChange(
  request: { valueKind?: ParameterValueKind; currentValue: string; targetValue: string },
  parameter?: { valueKind?: ParameterValueKind; configFormat?: string }
) {
  if (request.valueKind === "complex" || parameter?.valueKind === "complex") {
    return true;
  }

  if (parameter) {
    return shouldSummarizeComplexParameter(parameter, request.currentValue, request.targetValue);
  }

  return [request.currentValue, request.targetValue].some(
    (value) => {
      const normalized = value.trim();
      return normalized.length > 0 && isComplexParameterValue(normalized);
    }
  );
}

export function isAutoGeneratedChangeSummary(summary: string) {
  return /\bchanges from\b/i.test(summary);
}

export function isRedundantReviewSummary(summary: string) {
  const trimmed = summary.trim();
  if (!trimmed) {
    return true;
  }

  if (isAutoGeneratedChangeSummary(trimmed)) {
    return true;
  }

  return /为复杂配置（\d+ 行）/.test(trimmed) || /^将 .+ 从 .+ 调整为 .+。$/.test(trimmed);
}

export function shouldShowReviewDetailReason(reason: string) {
  const trimmed = reason.trim();
  if (!trimmed) {
    return false;
  }

  return !/^(Risk level:|Module:)\s/.test(trimmed);
}

export function buildReviewDetailSummary(input: {
  title: string;
  currentValue: string;
  targetValue: string;
  valueKind?: ParameterValueKind;
  configFormat?: string;
}) {
  const request = {
    valueKind: input.valueKind,
    currentValue: input.currentValue,
    targetValue: input.targetValue
  };
  const parameter =
    input.valueKind !== undefined || input.configFormat !== undefined
      ? { valueKind: input.valueKind, configFormat: input.configFormat }
      : undefined;

  if (shouldSummarizeReviewChange(request, parameter)) {
    const valueSummary = getParameterValueSummary(input.currentValue || input.targetValue);
    const differenceLabel = input.currentValue === input.targetValue ? "当前与目标一致" : "当前与目标不同";

    return {
      isComplex: true as const,
      headline: `${input.title} 为复杂配置（${valueSummary.lineCount} 行）`,
      differenceLabel,
      hasDifference: input.currentValue !== input.targetValue
    };
  }

  const current = input.currentValue.trim() || "-";
  const target = input.targetValue.trim() || "-";

  return {
    isComplex: false as const,
    headline: `将 ${input.title} 从 ${current} 调整为 ${target}。`
  };
}

export function getComplexParameterLineCount(value: string) {
  return value ? value.split(/\r?\n/).length : 0;
}

export function getComplexParameterKindLabel(parameter: { configFormat: string }) {
  const format = parameter.configFormat.trim();
  if (format.startsWith("DTS")) {
    return "DTS";
  }
  if (format.includes("string-list") || format.includes("profile")) {
    return "多行列表";
  }
  return "多行配置";
}

export function complexEditorRows(value: string, minRows = 6) {
  return Math.min(Math.max(minRows, getComplexParameterLineCount(value)), 16);
}
