import type { FrozenP0Graph } from "../types";
import { SAME_KEY_R6_R8_PROPERTY_KEY } from "../rules";

const ORG = "s7cls-org";
const SOURCE_SYSTEM = "wiseeff-v1";

const identity = (
  id: string,
  sourceKind: FrozenP0Graph["identities"][number]["sourceKind"],
  sourceId: string,
  ownerScopeKind: "platform" | "organization",
  ownerScopeId: string,
): FrozenP0Graph["identities"][number] => ({
  id,
  sourceSystem: SOURCE_SYSTEM,
  sourceKind,
  ownerScopeKind,
  ownerScopeId,
  sourceId,
});

export const FROZEN_P0_GRAPH_FIXTURE: FrozenP0Graph = {
  catalog: "parameter-catalog-p0-graph",
  identities: [
    identity("s7cls-lid-r0-cross", "parameter-spec", "s7cls-spec-r0-cross", "platform", "platform"),
    identity("s7cls-lid-r0-key", "parameter-spec", "s7cls-spec-r0-key", "platform", "platform"),
    identity("s7cls-lid-r1-status", "parameter-spec", "s7cls-spec-r1-status", "platform", "platform"),
    identity("s7cls-lid-r2-root", "parameter-spec", "s7cls-spec-r2-root", "platform", "platform"),
    identity("s7cls-lid-r2-schema", "driver-schema", "s7cls-schema-r2", "platform", "platform"),
    identity("s7cls-lid-r3-root", "parameter-spec", "s7cls-spec-r3-root", "platform", "platform"),
    identity("s7cls-lid-r4-driver", "parameter-spec", "s7cls-spec-r4-driver", "platform", "platform"),
    identity("s7cls-lid-r4-current", "parameter-spec-version", "s7cls-ver-r4-current", "platform", "platform"),
    identity("s7cls-lid-r4-old", "parameter-spec-version", "s7cls-ver-r4-old", "platform", "platform"),
    identity("s7cls-lid-r5-node", "parameter-spec", "s7cls-spec-r5-node", "platform", "platform"),
    identity("s7cls-lid-r6-twin", "parameter-spec", "s7cls-spec-r6-twin", "platform", "platform"),
    identity("s7cls-lid-r7-policy", "parameter-spec", "s7cls-spec-r7-policy", "organization", ORG),
    identity("s7cls-lid-r8-twin", "parameter-spec", "s7cls-spec-r8-twin", "organization", ORG),
    identity("s7cls-lid-r9-deprecated", "parameter-spec", "s7cls-spec-r9-deprecated", "platform", "platform"),
    identity("s7cls-lid-r10-unknown", "parameter-spec", "s7cls-spec-r10-unknown", "platform", "platform"),
  ],
  specs: [
    {
      id: "s7cls-spec-r0-cross",
      organizationId: null,
      sourceKind: "dts",
      specificationKey: "s7cls.r0.cross",
      attributionSubjectId: "s7cls-sub-r0-org-node",
      definitionLifecycle: "active",
      propertyKey: "s7cls,r0-cross",
    },
    {
      id: "s7cls-spec-r0-key",
      organizationId: null,
      sourceKind: "dts",
      specificationKey: "s7cls.r0.key",
      attributionSubjectId: "s7cls-sub-r4-driver",
      definitionLifecycle: "active",
      propertyKey: "s7cls,r0-spec-key",
    },
    {
      id: "s7cls-spec-r1-status",
      organizationId: null,
      sourceKind: "dts",
      specificationKey: "s7cls.r1.status",
      attributionSubjectId: null,
      definitionLifecycle: "active",
      propertyKey: "status",
    },
    {
      id: "s7cls-spec-r2-root",
      organizationId: null,
      sourceKind: "dts",
      specificationKey: "s7cls.r2.root",
      attributionSubjectId: "s7cls-sub-r4-driver",
      definitionLifecycle: "active",
      propertyKey: null,
    },
    {
      id: "s7cls-spec-r3-root",
      organizationId: null,
      sourceKind: "dts",
      specificationKey: "s7cls.r3.root",
      attributionSubjectId: null,
      definitionLifecycle: "active",
      propertyKey: null,
    },
    {
      id: "s7cls-spec-r4-driver",
      organizationId: null,
      sourceKind: "dts",
      specificationKey: "s7cls.r4.driver",
      attributionSubjectId: "s7cls-sub-r4-driver",
      definitionLifecycle: "active",
      propertyKey: "s7cls,driver-property",
    },
    {
      id: "s7cls-spec-r5-root",
      organizationId: null,
      sourceKind: "dts",
      specificationKey: "s7cls.r5.root",
      attributionSubjectId: "s7cls-sub-r5-node",
      definitionLifecycle: "active",
      propertyKey: null,
    },
    {
      id: "s7cls-spec-r5-node",
      organizationId: null,
      sourceKind: "dts",
      specificationKey: "s7cls.r5.node",
      attributionSubjectId: "s7cls-sub-r5-node",
      definitionLifecycle: "active",
      propertyKey: "s7cls,node-property",
    },
    {
      id: "s7cls-spec-r6-twin",
      organizationId: null,
      sourceKind: "dts",
      specificationKey: "s7cls.r6.twin",
      attributionSubjectId: null,
      definitionLifecycle: "draft",
      propertyKey: SAME_KEY_R6_R8_PROPERTY_KEY,
    },
    {
      id: "s7cls-spec-r7-policy",
      organizationId: ORG,
      sourceKind: "manual",
      specificationKey: "s7cls.r7.policy",
      attributionSubjectId: null,
      definitionLifecycle: "active",
      propertyKey: "s7cls,policy-override",
    },
    {
      id: "s7cls-spec-r8-twin",
      organizationId: ORG,
      sourceKind: "manual",
      specificationKey: "s7cls.r8.twin",
      attributionSubjectId: "s7cls-sub-r8-org-node",
      definitionLifecycle: "draft",
      propertyKey: SAME_KEY_R6_R8_PROPERTY_KEY,
    },
    {
      id: "s7cls-spec-r9-deprecated",
      organizationId: null,
      sourceKind: "dts",
      specificationKey: "s7cls.r9.deprecated",
      attributionSubjectId: null,
      definitionLifecycle: "deprecated",
      propertyKey: "s7cls,deprecated",
    },
    {
      id: "s7cls-spec-r10-unknown",
      organizationId: null,
      sourceKind: "dts",
      specificationKey: "s7cls.r10.unknown",
      attributionSubjectId: null,
      definitionLifecycle: "active",
      propertyKey: "s7cls,unknown",
    },
  ],
  specVersions: [
    {
      id: "s7cls-ver-r0-cross",
      parameterSpecId: "s7cls-spec-r0-cross",
      version: 1,
      lifecycle: "active",
      versionStatus: "active",
    },
    {
      id: "s7cls-ver-r0-key",
      parameterSpecId: "s7cls-spec-r0-key",
      version: 1,
      lifecycle: "active",
      versionStatus: "active",
    },
    {
      id: "s7cls-ver-r1-status",
      parameterSpecId: "s7cls-spec-r1-status",
      version: 1,
      lifecycle: "active",
      versionStatus: "active",
    },
    {
      id: "s7cls-ver-r2-root",
      parameterSpecId: "s7cls-spec-r2-root",
      version: 1,
      lifecycle: "active",
      versionStatus: "active",
    },
    {
      id: "s7cls-ver-r3-root",
      parameterSpecId: "s7cls-spec-r3-root",
      version: 1,
      lifecycle: "active",
      versionStatus: "active",
    },
    {
      id: "s7cls-ver-r4-old",
      parameterSpecId: "s7cls-spec-r4-driver",
      version: 1,
      lifecycle: "deprecated",
      versionStatus: "superseded",
    },
    {
      id: "s7cls-ver-r4-current",
      parameterSpecId: "s7cls-spec-r4-driver",
      version: 2,
      lifecycle: "active",
      versionStatus: "active",
    },
    {
      id: "s7cls-ver-r5-root",
      parameterSpecId: "s7cls-spec-r5-root",
      version: 1,
      lifecycle: "active",
      versionStatus: "active",
    },
    {
      id: "s7cls-ver-r5-node",
      parameterSpecId: "s7cls-spec-r5-node",
      version: 1,
      lifecycle: "active",
      versionStatus: "active",
    },
    {
      id: "s7cls-ver-r6-twin",
      parameterSpecId: "s7cls-spec-r6-twin",
      version: 1,
      lifecycle: "draft",
      versionStatus: "draft",
    },
    {
      id: "s7cls-ver-r7-policy",
      parameterSpecId: "s7cls-spec-r7-policy",
      version: 1,
      lifecycle: "active",
      versionStatus: "active",
    },
    {
      id: "s7cls-ver-r8-twin",
      parameterSpecId: "s7cls-spec-r8-twin",
      version: 1,
      lifecycle: "draft",
      versionStatus: "draft",
    },
    {
      id: "s7cls-ver-r9-deprecated",
      parameterSpecId: "s7cls-spec-r9-deprecated",
      version: 1,
      lifecycle: "deprecated",
      versionStatus: "superseded",
    },
    {
      id: "s7cls-ver-r10-unknown",
      parameterSpecId: "s7cls-spec-r10-unknown",
      version: 1,
      lifecycle: "active",
      versionStatus: "active",
    },
  ],
  subjects: [
    {
      id: "s7cls-sub-r0-org-node",
      organizationId: ORG,
      subjectKind: "node-type-definition",
    },
    {
      id: "s7cls-sub-r4-driver",
      organizationId: null,
      subjectKind: "driver-registration",
    },
    {
      id: "s7cls-sub-r5-node",
      organizationId: null,
      subjectKind: "node-type-definition",
    },
    {
      id: "s7cls-sub-r8-org-node",
      organizationId: ORG,
      subjectKind: "node-type-definition",
    },
  ],
  driverRegistrations: [{ attributionSubjectId: "s7cls-sub-r4-driver" }],
  nodeTypeDefinitions: [
    { attributionSubjectId: "s7cls-sub-r0-org-node" },
    { attributionSubjectId: "s7cls-sub-r5-node" },
    { attributionSubjectId: "s7cls-sub-r8-org-node" },
  ],
  driverSchemas: [
    {
      id: "s7cls-schema-r2",
      parameterSpecId: "s7cls-spec-r2-root",
      organizationId: null,
      attributionSubjectId: "s7cls-sub-r4-driver",
    },
    {
      id: "s7cls-schema-r3",
      parameterSpecId: "s7cls-spec-r3-root",
      organizationId: null,
      attributionSubjectId: null,
    },
    {
      id: "s7cls-schema-r5",
      parameterSpecId: "s7cls-spec-r5-root",
      organizationId: null,
      attributionSubjectId: "s7cls-sub-r5-node",
    },
  ],
  driverSchemaVersions: [
    { id: "s7cls-sver-r2", driverSchemaId: "s7cls-schema-r2", lifecycle: "active" },
    { id: "s7cls-sver-r3", driverSchemaId: "s7cls-schema-r3", lifecycle: "active" },
    { id: "s7cls-sver-r5", driverSchemaId: "s7cls-schema-r5", lifecycle: "active" },
  ],
  dtsPropertySpecs: [
    {
      id: "s7cls-dps-r0-cross",
      parameterSpecId: "s7cls-spec-r0-cross",
      driverSchemaId: null,
      propertyKey: "s7cls,r0-cross",
    },
    {
      id: "s7cls-dps-r0-key",
      parameterSpecId: "s7cls-spec-r0-key",
      driverSchemaId: "s7cls-schema-r2",
      propertyKey: "s7cls,r0-dts-key",
    },
    {
      id: "s7cls-dps-r4-driver",
      parameterSpecId: "s7cls-spec-r4-driver",
      driverSchemaId: "s7cls-schema-r2",
      propertyKey: "s7cls,driver-property",
    },
    {
      id: "s7cls-dps-r5-node",
      parameterSpecId: "s7cls-spec-r5-node",
      driverSchemaId: "s7cls-schema-r5",
      propertyKey: "s7cls,node-property",
    },
    {
      id: "s7cls-dps-r6-twin",
      parameterSpecId: "s7cls-spec-r6-twin",
      driverSchemaId: null,
      propertyKey: SAME_KEY_R6_R8_PROPERTY_KEY,
    },
    {
      id: "s7cls-dps-r8-twin",
      parameterSpecId: "s7cls-spec-r8-twin",
      driverSchemaId: null,
      propertyKey: SAME_KEY_R6_R8_PROPERTY_KEY,
    },
  ],
  modules: [
    {
      id: "s7cls-mod-business",
      organizationId: ORG,
      kind: "business",
      origin: "curated",
      name: "S7-CLS Business",
      attributionSubjectId: null,
    },
    {
      id: "s7cls-mod-driver",
      organizationId: ORG,
      kind: "driver-group",
      origin: "curated",
      name: "S7-CLS Driver Group",
      attributionSubjectId: "s7cls-sub-r4-driver",
    },
    {
      id: "s7cls-mod-node",
      organizationId: ORG,
      kind: "node-type",
      origin: "curated",
      name: "S7-CLS NodeType",
      attributionSubjectId: "s7cls-sub-r5-node",
    },
    {
      id: "s7cls-mod-r8-node",
      organizationId: ORG,
      kind: "node-type",
      origin: "curated",
      name: "S7-CLS Org NodeType",
      attributionSubjectId: "s7cls-sub-r8-org-node",
    },
  ],
  placements: [
    {
      id: "s7cls-place-r4",
      organizationId: ORG,
      attributionSubjectId: "s7cls-sub-r4-driver",
      driverGroupModuleId: "s7cls-mod-driver",
    },
  ],
  bindings: [],
  bindingRevisions: [],
};

export const FROZEN_P0_GRAPH_SHA256 =
  "7bf5e870a697fda5ed39ff6c705034990e2194abc3b621e6db3d09a8b40e7678";

export const EXPECTED_P0_CLASS_BY_IDENTITY = {
  "s7cls-lid-r0-cross": "R0",
  "s7cls-lid-r0-key": "R0",
  "s7cls-lid-r1-status": "R1",
  "s7cls-lid-r2-root": "R2",
  "s7cls-lid-r2-schema": "R2",
  "s7cls-lid-r3-root": "R3",
  "s7cls-lid-r4-driver": "R4",
  "s7cls-lid-r4-current": "R4",
  "s7cls-lid-r4-old": "R9",
  "s7cls-lid-r5-node": "R5",
  "s7cls-lid-r6-twin": "R6",
  "s7cls-lid-r7-policy": "R7",
  "s7cls-lid-r8-twin": "R8",
  "s7cls-lid-r9-deprecated": "R9",
  "s7cls-lid-r10-unknown": "R10",
} as const;
